### ISSUE TITLE
Null Pointer Console Spam

### ISSUE THREAD

**Issue by Alaberti** [WildBamaBoy/radix-core#12]
I keep seeing this in the console over and over and I'm not sure what's up. Radix Core 2.0.1, MCA 5.0.5_1, forge 1403.

-----
[17:51:27] [Server thread/ERROR] [RadixCore]: Unexpected exception/(Error sending sync data to client.). null
[17:51:30] [Server thread/WARN]: Fetching addPacket for removed entity
[17:51:55] [Server thread/ERROR] [RadixCore]: catching
java.lang.NullPointerException
	at radixcore.packets.PacketDataSyncReq.onMessage(PacketDataSyncReq.java:42) [PacketDataSyncReq.class:?]
	at radixcore.packets.PacketDataSyncReq.onMessage(PacketDataSyncReq.java:11) [PacketDataSyncReq.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) [SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) [SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:51:55] [Server thread/ERROR] [RadixCore]: Unexpected exception/(Error sending sync data to client.). null

**Comment by Alaberti** [comment]
Still seeing this issue. I am connected to a dedicated server, seeing this issue on the client-side console. 
Radix-Core 2.0.2, MCA 5.0.6, Forge 1408. Good news, it no longer has this line: 
[17:51:30] [Server thread/WARN]: Fetching addPacket for removed entity
