### ISSUE TITLE
bound must be positive

### ISSUE THREAD

**Issue by SkyBlade1978** [WildBamaBoy/radix-core#35]
Seeing these in the log, in came I have an invisible warrior...

[16:57:39] [Server thread/ERROR] [RadixCore/]: catching
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_11]
	at radixcore.util.RadixMath.getNumberInRange(RadixMath.java:24) ~[RadixMath.class:?]
	at mca.enums.EnumProfessionGroup.getSkin(EnumProfessionGroup.java:61) [EnumProfessionGroup.class:?]
	at mca.enums.EnumProfessionGroup.getMaleSkin(EnumProfessionGroup.java:92) [EnumProfessionGroup.class:?]
	at mca.entity.EntityHuman.getRandomSkin(EntityHuman.java:348) [EntityHuman.class:?]
	at mca.entity.EntityHuman.<init>(EntityHuman.java:200) [EntityHuman.class:?]
	at sun.reflect.GeneratedConstructorAccessor68.newInstance(Unknown Source) [?:1.8.0_11]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_11]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_11]
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:163) [ry.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:597) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:524) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:474) [atj.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [aid.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) [aid.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:842) [aid.class:?]
	at net.minecraft.block.BlockFire.tryCatchFire(BlockFire.java:274) [aly.class:?]
	at net.minecraft.block.BlockFire.func_180650_b(BlockFire.java:193) [aly.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744) [ls.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_11]
[16:57:39] [Server thread/ERROR] [RadixCore/]: Unexpected exception/(Unable to generate random skin for skin group <Warrior>!). bound must be positive

**Comment by WildBamaBoy** [comment]
MCA related.
